language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
before_install:
  - cat ~/.m2/settings.xml
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
  # https://github.com/travis-ci/travis-ci/issues/4629
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: true
script: mvn clean install
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_failure: always
