language: java
jdk:
  - oraclejdk8
script: mvn -fae -U -B clean install -P check -P snapshot-dist
#after_success: chmod +x .travis/on_success.sh && .travis/on_success.sh
cache:
  directories
    - $HOME/.m2
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_failure: always
